[package]
name = "example_02"
version = "0.1.0"
authors = ["Inmo Jang <inmo.jang@manchester.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
optimization_engine = "0.6.2"
rand = "0.3.14"